Repository kowainik/eio, pull requests merged in 2021-03, with the labels that each got.

#2 Update to 9.0
  .github/workflows/ci.yml
  eio.cabal
Labels: CI

#3 [#1] Write initial EIO interface
  eio.cabal
  src/EIO.hs
  src/Eio.hs
Labels: enhancement

#9 [#8] Create README with an example
  README.lhs
  README.md
  eio.cabal
Labels: documentation

#11 More accurate type for catch
  src/EIO.hs
Labels: enhancement
